# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160315_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Userprof',
            },
        ),
    ]
