# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_userquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestions',
            old_name='content',
            new_name='question',
        ),
    ]
