# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_comprehension_maths_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentprof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('subject1', models.TextField(blank=True, null=True)),
                ('subject2', models.TextField(blank=True, null=True)),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
