# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_studentprof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprof',
            old_name='score1',
            new_name='composition',
        ),
        migrations.RenameField(
            model_name='studentprof',
            old_name='subject1',
            new_name='compre',
        ),
        migrations.RenameField(
            model_name='studentprof',
            old_name='score2',
            new_name='creative',
        ),
        migrations.RenameField(
            model_name='studentprof',
            old_name='subject2',
            new_name='vocab',
        ),
        migrations.AddField(
            model_name='studentprof',
            name='da',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='ds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='dwe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='ed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='handwriting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='lm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='punctuation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='rg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='spelling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='stl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprof',
            name='wordreading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
