# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170215_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='composition',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('all_id', models.IntegerField(blank=True, null=True)),
                ('std', models.IntegerField(blank=True, null=True)),
                ('q_text', models.TextField(blank=True, null=True)),
                ('ans', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
