# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_composition_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='standard',
            field=models.TextField(blank=True, null=True),
        ),
    ]
