# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='null', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='synopsis',
            field=models.TextField(default='null'),
        ),
    ]
